/*  Descripción corta de cada producto (1–2 oraciones), por id de js/app.js.
 *  Se muestra en la ficha debajo de "Presentación" y alimenta la meta description
 *  y el JSON-LD. Editar acá y volver a correr:  node tools/build-seo.mjs
 *
 *  Nota: son textos generales de cada línea/marca, sin porcentajes ni claims
 *  nutricionales precisos. Conviene que el cliente los revise contra el envase.
 */
export default {
  /* ── Gatos ── */
  g01: "Alimento completo para gatos castrados y esterilizados, formulado para ayudar a controlar el peso y cuidar el tracto urinario.",
  g02: "Ración premium para gatos castrados, con proteína de calidad y control de calorías para evitar el sobrepeso después de la castración.",
  g03: "Ración premium para gatos adultos de todas las razas, nutrición completa y balanceada para el día a día, con kilo de regalo.",
  g04: "Ración premium para gatos adultos con sabor a pescado, formulada para piel sana y pelaje brillante.",
  g05: "Ración premium para gatos adultos sabor carne, alimento completo y balanceado con alta aceptación.",
  g06: "Ración premium para gatos adultos sabor pescado, en presentación con 1 kg de regalo.",
  g07: "Ración premium para gatos adultos, nutrición completa en una bolsa práctica de 5 kg.",
  g08: "Alimento económico para gatos adultos, balanceado para la alimentación diaria.",
  g09: "Ración para gatos adultos de todas las razas, alimento completo con buena relación precio–calidad.",
  g10: "Alimento balanceado para gatos adultos, fórmula estándar para la alimentación diaria.",
  g11: "Ración económica para gatos adultos, nutrición completa para el día a día.",
  g12: "Ración super premium para gatos adultos, con proteínas de alta calidad, prebióticos y cuidado del sistema urinario.",
  g13: "Piedra sanitaria absorbente para gatos, controla olores y es fácil de limpiar.",
  g14: "Piedra sanitaria aglomerante de alta absorción, forma bloques compactos y neutraliza el olor.",
  g15: "Piedra sanitaria absorbente para gatos, presentación económica para la bandeja de todos los días.",
  g16: "Piedra sanitaria de alta absorción que controla olores por más tiempo.",
  g17: "Piedra sanitaria absorbente en presentación chica, ideal para probar o para un solo gato.",
  g18: "Piedra sanitaria absorbente en bolsa grande de 6 kg, rinde más y reduce el olor de la bandeja.",

  /* ── Perros ── */
  p01: "Ración para perros adultos de todas las razas, alimento completo y balanceado para el día a día.",
  p02: "Ración para perros adultos de todas las razas en bolsa de 25 kg, la opción más rendidora para casas con varios perros.",
  p03: "Alimento balanceado para perros adultos, fórmula estándar con buena relación precio–calidad.",
  p04: "Alimento balanceado para perros adultos en bolsa grande, con 3 kg de regalo.",
  p05: "Ración económica para perros adultos, nutrición completa para la alimentación diaria.",
  p06: "Ración económica para perros adultos en combo de 25 kg + 7 kg de regalo, ideal para varios perros.",
  p07: "Ración para cachorros, con la energía y el calcio que necesitan en la etapa de crecimiento.",
  p08: "Ración premium para perros adultos con proteína de calidad, formulada para mantener la vitalidad y el buen estado del pelaje.",
  p09: "Ración premium para perros adultos de todas las razas, alimento completo y balanceado.",
  p10: "Ración premium para perros adultos en combo de 25 kg + 10 kg de regalo, la mejor relación precio por kilo.",
  p11: "Ración premium para perros adultos de todas las razas, con 2 kg de regalo.",
  p12: "Alimento económico para perros adultos, balanceado para la alimentación diaria.",
  p13: "Ración premium especial para perros adultos de razas pequeñas, croqueta chica y alta energía.",
  p14: "Ración premium especial para perros adultos de razas pequeñas en bolsa de 14 kg.",
  p15: "Ración premium especial para perros mayores de 7 años, con cuidado de articulaciones y menor aporte calórico.",
  p16: "Ración premium especial para perros senior (7+), en bolsa de 14 kg con 2 kg de regalo.",
  p17: "Ración premium especial para perros adultos, con proteína de calidad, salud oral y cuidado de piel y pelaje.",
  p18: "Alimento económico para perros adultos, para la alimentación de todos los días.",
  p19: "Alimento balanceado para perros adultos, fórmula estándar y buen rendimiento.",
  p20: "Alimento balanceado para perros adultos en bolsa de 20 kg + 2 kg de regalo.",
  p21: "Alimento económico para perros adultos, nutrición completa a bajo costo.",
  p22: "Alimento económico para perros adultos, balanceado para el día a día.",
  p23: "Ración para perros adultos de todas las razas, alimento completo y balanceado.",
  p24: "Ración para perros adultos de todas las razas en bolsa de 20 kg.",
  p25: "Ración light para perros adultos con tendencia al sobrepeso o poca actividad, menos calorías sin perder nutrientes.",
  p26: "Ración light para perros adultos en bolsa de 15 kg + 2 kg de regalo, para el control de peso.",
  p27: "Ración para cachorros de todas las razas, con la energía, el calcio y las proteínas del crecimiento.",
  p28: "Ración para cachorros en bolsa de 15 kg + 2 kg de regalo.",
  p29: "Ración para perros adultos de razas pequeñas, croqueta chica adaptada a su boca y su metabolismo.",
  p30: "Ración para perros adultos de todas las razas, la fórmula clásica de la marca.",
  p31: "Ración premium para perros adultos de todas las razas, alimento completo y balanceado.",
  p32: "Ración para perros adultos de todas las razas en bolsa de 25 kg, muy rendidora.",
  p33: "Ración premium light para perros adultos de razas pequeñas, para controlar el peso con croqueta chica.",
  p34: "Ración premium para perros adultos de razas pequeñas, en bolsa de 15 kg.",
  p35: "Ración premium para perros adultos de razas pequeñas, en bolsa de 10,1 kg.",
  p36: "Ración premium para perros adultos de razas grandes, con cuidado de articulaciones y 2 kg de regalo.",
  p37: "Ración premium para cachorros, con proteínas de calidad para el desarrollo, en bolsa con 2 kg de regalo.",
  p38: "Pedigree para perros adultos de todas las razas, sabor carne y vegetales, con vitaminas y minerales para huesos fuertes.",
  p39: "Ración gourmet saborizada con cordero para perros adultos, en bolsa de 15 kg + 1,5 kg de regalo.",
  p40: "Ración super premium para perros adultos de razas pequeñas, con croqueta chica, prebióticos y cuidado dental.",
  p41: "Ración super premium para perros adultos de razas medianas, con 3 kg de regalo.",
  p42: "Ración super premium para perros adultos de razas medianas, en bolsa de 15 kg.",
  p43: "Ración para perros adultos de todas las razas en bolsa de 22 kg + 2 kg de regalo.",
  p44: "Ración para perros adultos en combo de 22 kg + 10 kg de regalo, ideal para casas con varios perros.",
  p45: "Ración para perros adultos de todas las razas, alimento completo en bolsa de 22 kg.",
  p46: "Ración para perros adultos de todas las razas, alimento completo y balanceado en bolsa de 21 kg.",
  p47: "Ración para perros adultos, alimento balanceado nacional en bolsa de 22 kg.",
  p48: "Ración para perros adultos de todas las razas, en bolsa de 16 kg + 2 kg de regalo.",
  p49: "Ración económica para perros adultos en bolsa de 25 kg, la opción más rendidora.",

  /* ── Granja ── */
  f01: "Ración granulada para gallinas ponedoras en su primera fase de postura, formulada para sostener la producción de huevos.",
  f02: "Ración molida para gallinas ponedoras en segunda fase de postura, con calcio para la calidad de la cáscara.",
  f03: "Ración granulada para gallinas ponedoras en segunda fase de postura, con calcio para la calidad de la cáscara.",
  f04: "Ración para pollas en recría, la etapa previa a la postura, para un buen desarrollo corporal.",
  f05: "Ración iniciadora para pollitos bebé, con alta proteína para las primeras semanas de vida.",
  f06: "Ración de terminación para pollos parrilleros, formulada para el engorde final.",
  f07: "Ración de mantenimiento para vacunos adultos, complemento energético y proteico del pastoreo.",
  f08: "Ración para terneros en destete y recría, con proteína y energía para el crecimiento.",
  f09: "Ración para cerdos en etapa de engorde, formulada para una buena conversión alimenticia.",
  f10: "Ración iniciadora para lechones, de fácil digestión para las primeras semanas.",
  f11: "Ración para cerdas gestantes y lactantes, con el aporte que necesitan durante la gestación y la cría.",
  f12: "Ración para ovinos, complemento del pastoreo en engorde, gestación o épocas de escasez de pasto.",
  f13: "Ración completa para conejos, con fibra y nutrientes para todas las etapas.",
  f14: "Suplemento proteico concentrado para mezclar con grano y mejorar la dieta de aves, cerdos o vacunos.",
  f15: "Suplemento vitamínico y mineral para reforzar la alimentación de animales de granja.",

  /* ── Granos ── */
  s01: "Arroz en bolsa de 25 kg para la alimentación animal, fuente de energía de fácil digestión.",
  s02: "Maíz entero en bolsa de 25 kg, el grano energético básico para aves, cerdos y vacunos.",
  s03: "Maíz quebrado en bolsa de 25 kg, más fácil de comer para pollos, gallinas y animales chicos.",
  s04: "Avena en bolsa de 35 kg, el grano clásico para caballos: energía y fibra.",

  /* ── Sanidad ── */
  c01: "Pipeta antiparasitaria de uso externo contra pulgas y garrapatas, se aplica sobre la piel.",
  c02: "Comprimido masticable mensual para perros de 5 a 10 kg contra pulgas, garrapatas, gusano del corazón y parásitos intestinales.",
  c03: "Comprimido masticable mensual para perros de 20 a 40 kg contra pulgas, garrapatas, gusano del corazón y parásitos intestinales.",
  c04: "Comprimido masticable mensual para perros de 10 a 20 kg contra pulgas, garrapatas, gusano del corazón y parásitos intestinales.",
  c05: "Comprimido masticable mensual para perros de 40 a 60 kg contra pulgas, garrapatas, gusano del corazón y parásitos intestinales.",
  c06: "Gel cebo para cucarachas: se aplica en puntos y elimina la colonia. Jeringa de 30 g.",
  c07: "Antiparasitario de amplio espectro para parásitos internos y externos, en frasco. Consultá dosis con el veterinario.",
  c08: "Veneno granulado para hormigas, se esparce sobre el hormiguero y los caminos.",
  c09: "Veneno en polvo para hormigas, de acción rápida sobre el hormiguero.",
  c10: "Auxiliar educativo para cachorros: atrae al perro al lugar donde querés que haga sus necesidades.",
  c11: "Producto para eliminar pulgas y garrapatas en perros y gatos, de uso tópico.",

  /* ── Harinas ── */
  h01: "Harina de trigo común en bolsa de 25 kg, para panificación y uso general.",
  h02: "Harina de trigo 0000 en bolsa de 25 kg, la más refinada: ideal para pastelería, masas finas y pizzas.",
  h03: "Harina de trigo 000 en bolsa de 25 kg, la clásica para pan, facturas y masas con levadura.",
  h04: "Harina de trigo 00 en bolsa de 25 kg, para panes rústicos y masas más firmes.",
  h05: "Harina de trigo integral en bolsa de 25 kg, con salvado, para panes y masas integrales.",
  h06: "Pack de 12 paquetes de Harina Uruguay 0000 de 1 kg, para reventa en almacenes y comercios.",
  h07: "Pack de 12 paquetes de Harina Primor 0000 de 1 kg, para reventa en almacenes y comercios."
};
